### ISSUE TITLE
Game crashed when trying to get the last sword

### ISSUE THREAD

**Issue by motss** [mkiisoft/taphero_web#1]
I think after long usage the web app fails to handle more user taps and everything feels sluggish eventually it crashes. I lost my game state forcing me to start over.

It might be due to busy main thread and large memory usage.

Was playing on Pixel 3 XL.

**Comment by mkiisoft** [comment]
Are you using it with Chrome? There's a Chrome bug when trying to handle more than one finger at the time. Try it on Safari and Firefox to be sure.
